import * as React from 'react';
import { cn } from '../../lib/utils';
const Card = React.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={cn('rounded-xl border border-[#E2E8F0] bg-white text-[#172033] shadow-xs', className)} {...props}/>));
Card.displayName = 'Card';
const CardHeader = React.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={cn('flex flex-col space-y-1.5 p-5', className)} {...props}/>));
CardHeader.displayName = 'CardHeader';
const CardTitle = React.forwardRef(({ className, ...props }, ref) => (<h3 ref={ref} className={cn('text-base font-bold leading-none tracking-tight text-[#172033]', className)} {...props}/>));
CardTitle.displayName = 'CardTitle';
const CardDescription = React.forwardRef(({ className, ...props }, ref) => (<p ref={ref} className={cn('text-xs text-[#526176]', className)} {...props}/>));
CardDescription.displayName = 'CardDescription';
const CardContent = React.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={cn('p-5 pt-0', className)} {...props}/>));
CardContent.displayName = 'CardContent';
const CardFooter = React.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={cn('flex items-center p-5 pt-0 border-t border-slate-100 mt-4', className)} {...props}/>));
CardFooter.displayName = 'CardFooter';
export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };
